# Generated by Django 2.0 on 2017-12-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='added_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
